# -*- coding: utf-8 -*-
"""irwa_ final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PevVJhGTO11syXacx6aiIYpsZVeKK1_x
"""

import pandas as pd

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (classification_report, confusion_matrix,
                             precision_recall_curve, roc_curve, auc,
                             f1_score, precision_score, recall_score,
                             roc_auc_score, average_precision_score)
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
import xgboost as xgb
from sklearn.ensemble import RandomForestClassifier
import shap
import json
import warnings
warnings.filterwarnings('ignore')

print("Libraries imported successfully!")

df = pd.read_csv('/content/drive/MyDrive/base_txns_10k_ml_slim.csv')

# Cell 1: Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, RobustScaler
from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor
from sklearn.svm import OneClassSVM
from sklearn.model_selection import ParameterGrid
from sklearn.metrics import (classification_report, confusion_matrix,
                             precision_score, recall_score, f1_score,
                             roc_auc_score, average_precision_score)
import warnings
warnings.filterwarnings('ignore')

print("✅ Libraries imported for hyperparameter tuning!")

# Cell 2: Prepare Data
feature_cols = ['step', 'amount', 'amount_log', 'day', 'hour',
                'type_CASH_IN', 'type_CASH_OUT', 'type_DEBIT',
                'type_PAYMENT', 'type_TRANSFER']

X = df[feature_cols].copy()
y = df['isFraud'].copy()

# Convert boolean to int
bool_cols = X.select_dtypes(include=['bool']).columns
X[bool_cols] = X[bool_cols].astype(int)

# Try RobustScaler (better for outliers)
scaler = RobustScaler()
X_scaled = scaler.fit_transform(X)

print(f"Dataset: {X.shape}, Frauds: {y.sum()}")
print("✅ Using RobustScaler (better for anomaly detection)")

# Cell 3: Hyperparameter Tuning - Isolation Forest
print("\n" + "="*60)
print("HYPERPARAMETER TUNING - ISOLATION FOREST")
print("="*60)

# Define parameter grid
iso_param_grid = {
    'n_estimators': [100, 200, 300],
    'contamination': [0.01, 0.02, 0.03, 0.05],  # More aggressive
    'max_samples': ['auto', 256, 512],
    'max_features': [0.5, 0.75, 1.0]
}

best_iso_f1 = 0
best_iso_params = None
best_iso_model = None
best_iso_scores = None

print(f"Testing {len(list(ParameterGrid(iso_param_grid)))} parameter combinations...")
print("This may take a few minutes...\n")

for i, params in enumerate(ParameterGrid(iso_param_grid), 1):
    if i % 10 == 0:
        print(f"Progress: {i}/{len(list(ParameterGrid(iso_param_grid)))}")

    model = IsolationForest(
        n_estimators=params['n_estimators'],
        contamination=params['contamination'],
        max_samples=params['max_samples'],
        max_features=params['max_features'],
        random_state=42,
        n_jobs=-1
    )

    model.fit(X_scaled)
    pred = (model.predict(X_scaled) == -1).astype(int)

    f1 = f1_score(y, pred, zero_division=0)

    if f1 > best_iso_f1:
        best_iso_f1 = f1
        best_iso_params = params
        best_iso_model = model
        scores = model.score_samples(X_scaled)
        best_iso_scores = 1 - (scores - scores.min()) / (scores.max() - scores.min())

print("\n✅ Best Isolation Forest Parameters:")
for param, value in best_iso_params.items():
    print(f"   {param}: {value}")
print(f"   Best F1-Score: {best_iso_f1:.4f}")

# Evaluate best model
iso_pred = (best_iso_model.predict(X_scaled) == -1).astype(int)
iso_precision = precision_score(y, iso_pred, zero_division=0)
iso_recall = recall_score(y, iso_pred, zero_division=0)
iso_roc_auc = roc_auc_score(y, best_iso_scores)

print(f"\nBest Isolation Forest Performance:")
print(f"Precision: {iso_precision:.4f}")
print(f"Recall   : {iso_recall:.4f}")
print(f"F1-Score : {best_iso_f1:.4f}")
print(f"ROC-AUC  : {iso_roc_auc:.4f}")

cm_iso = confusion_matrix(y, iso_pred)
print(f"\nDetected: {cm_iso[1,1]}/{y.sum()} frauds")
print(f"False Alarms: {cm_iso[0,1]}")

# Cell 4: Hyperparameter Tuning - LOF
print("\n" + "="*60)
print("HYPERPARAMETER TUNING - LOCAL OUTLIER FACTOR")
print("="*60)

lof_param_grid = {
    'n_neighbors': [10, 20, 30, 50],
    'contamination': [0.01, 0.02, 0.03, 0.05],
    'metric': ['euclidean', 'manhattan', 'minkowski']
}

best_lof_f1 = 0
best_lof_params = None
best_lof_scores = None
best_lof_pred = None

print(f"Testing {len(list(ParameterGrid(lof_param_grid)))} parameter combinations...")

for i, params in enumerate(ParameterGrid(lof_param_grid), 1):
    if i % 10 == 0:
        print(f"Progress: {i}/{len(list(ParameterGrid(lof_param_grid)))}")

    model = LocalOutlierFactor(
        n_neighbors=params['n_neighbors'],
        contamination=params['contamination'],
        metric=params['metric'],
        novelty=False,
        n_jobs=-1
    )

    pred = (model.fit_predict(X_scaled) == -1).astype(int)
    f1 = f1_score(y, pred, zero_division=0)

    if f1 > best_lof_f1:
        best_lof_f1 = f1
        best_lof_params = params
        best_lof_pred = pred
        scores = -model.negative_outlier_factor_
        best_lof_scores = (scores - scores.min()) / (scores.max() - scores.min())

print("\n✅ Best LOF Parameters:")
for param, value in best_lof_params.items():
    print(f"   {param}: {value}")
print(f"   Best F1-Score: {best_lof_f1:.4f}")

lof_precision = precision_score(y, best_lof_pred, zero_division=0)
lof_recall = recall_score(y, best_lof_pred, zero_division=0)
lof_roc_auc = roc_auc_score(y, best_lof_scores)

print(f"\nBest LOF Performance:")
print(f"Precision: {lof_precision:.4f}")
print(f"Recall   : {lof_recall:.4f}")
print(f"F1-Score : {best_lof_f1:.4f}")
print(f"ROC-AUC  : {lof_roc_auc:.4f}")

cm_lof = confusion_matrix(y, best_lof_pred)
print(f"\nDetected: {cm_lof[1,1]}/{y.sum()} frauds")
print(f"False Alarms: {cm_lof[0,1]}")

# Cell 5: Hyperparameter Tuning - One-Class SVM
print("\n" + "="*60)
print("HYPERPARAMETER TUNING - ONE-CLASS SVM")
print("="*60)

ocsvm_param_grid = {
    'kernel': ['rbf', 'poly', 'sigmoid'],
    'nu': [0.01, 0.02, 0.03, 0.05],
    'gamma': ['scale', 'auto', 0.01, 0.1]
}

best_ocsvm_f1 = 0
best_ocsvm_params = None
best_ocsvm_model = None
best_ocsvm_scores = None

print(f"Testing {len(list(ParameterGrid(ocsvm_param_grid)))} parameter combinations...")

for i, params in enumerate(ParameterGrid(ocsvm_param_grid), 1):
    if i % 10 == 0:
        print(f"Progress: {i}/{len(list(ParameterGrid(ocsvm_param_grid)))}")

    model = OneClassSVM(
        kernel=params['kernel'],
        nu=params['nu'],
        gamma=params['gamma'],
        cache_size=1000
    )

    model.fit(X_scaled)
    pred = (model.predict(X_scaled) == -1).astype(int)

    f1 = f1_score(y, pred, zero_division=0)

    if f1 > best_ocsvm_f1:
        best_ocsvm_f1 = f1
        best_ocsvm_params = params
        best_ocsvm_model = model
        scores = -model.decision_function(X_scaled)
        best_ocsvm_scores = (scores - scores.min()) / (scores.max() - scores.min())

print("\n✅ Best One-Class SVM Parameters:")
for param, value in best_ocsvm_params.items():
    print(f"   {param}: {value}")
print(f"   Best F1-Score: {best_ocsvm_f1:.4f}")

ocsvm_pred = (best_ocsvm_model.predict(X_scaled) == -1).astype(int)
ocsvm_precision = precision_score(y, ocsvm_pred, zero_division=0)
ocsvm_recall = recall_score(y, ocsvm_pred, zero_division=0)
ocsvm_roc_auc = roc_auc_score(y, best_ocsvm_scores)

print(f"\nBest One-Class SVM Performance:")
print(f"Precision: {ocsvm_precision:.4f}")
print(f"Recall   : {ocsvm_recall:.4f}")
print(f"F1-Score : {best_ocsvm_f1:.4f}")
print(f"ROC-AUC  : {ocsvm_roc_auc:.4f}")

cm_ocsvm = confusion_matrix(y, ocsvm_pred)
print(f"\nDetected: {cm_ocsvm[1,1]}/{y.sum()} frauds")
print(f"False Alarms: {cm_ocsvm[0,1]}")

# Cell 6: Compare Tuned Models
print("\n" + "="*60)
print("TUNED MODELS COMPARISON")
print("="*60)

tuned_comparison = pd.DataFrame({
    'Model': ['Isolation Forest', 'LOF', 'One-Class SVM'],
    'Precision': [iso_precision, lof_precision, ocsvm_precision],
    'Recall': [iso_recall, lof_recall, ocsvm_recall],
    'F1-Score': [best_iso_f1, best_lof_f1, best_ocsvm_f1],
    'ROC-AUC': [iso_roc_auc, lof_roc_auc, ocsvm_roc_auc],
    'Frauds_Detected': [cm_iso[1,1], cm_lof[1,1], cm_ocsvm[1,1]],
    'False_Positives': [cm_iso[0,1], cm_lof[0,1], cm_ocsvm[0,1]]
})

print("\n", tuned_comparison.to_string(index=False))

# Cell 7: Optimized Ensemble with Weighted Voting
print("\n" + "="*60)
print("CREATING OPTIMIZED ENSEMBLE")
print("="*60)

# Test different weight combinations
weight_grid = [
    {'iso': 0.5, 'lof': 0.3, 'ocsvm': 0.2},
    {'iso': 0.4, 'lof': 0.4, 'ocsvm': 0.2},
    {'iso': 0.4, 'lof': 0.3, 'ocsvm': 0.3},
    {'iso': 0.6, 'lof': 0.2, 'ocsvm': 0.2},
    {'iso': 0.33, 'lof': 0.33, 'ocsvm': 0.34}
]

best_ensemble_f1 = 0
best_weights = None
best_ensemble_score = None

for weights in weight_grid:
    ensemble_score = (
        weights['iso'] * best_iso_scores +
        weights['lof'] * best_lof_scores +
        weights['ocsvm'] * best_ocsvm_scores
    )

    # Find optimal threshold
    thresholds = np.percentile(ensemble_score, np.arange(90, 99, 0.5))
    for threshold in thresholds:
        pred = (ensemble_score >= threshold).astype(int)
        f1 = f1_score(y, pred, zero_division=0)

        if f1 > best_ensemble_f1:
            best_ensemble_f1 = f1
            best_weights = weights
            best_ensemble_score = ensemble_score
            best_ensemble_threshold = threshold

print("✅ Best Ensemble Weights:")
for model, weight in best_weights.items():
    print(f"   {model}: {weight}")
print(f"\nOptimal Threshold: {best_ensemble_threshold:.4f}")

# Evaluate best ensemble
ensemble_pred = (best_ensemble_score >= best_ensemble_threshold).astype(int)
ensemble_precision = precision_score(y, ensemble_pred, zero_division=0)
ensemble_recall = recall_score(y, ensemble_pred, zero_division=0)
ensemble_f1 = f1_score(y, ensemble_pred, zero_division=0)
ensemble_roc_auc = roc_auc_score(y, best_ensemble_score)
ensemble_pr_auc = average_precision_score(y, best_ensemble_score)

print(f"\n📊 Optimized Ensemble Performance:")
print(f"Precision: {ensemble_precision:.4f}")
print(f"Recall   : {ensemble_recall:.4f}")
print(f"F1-Score : {ensemble_f1:.4f}")
print(f"ROC-AUC  : {ensemble_roc_auc:.4f}")
print(f"PR-AUC   : {ensemble_pr_auc:.4f}")

cm_ensemble = confusion_matrix(y, ensemble_pred)
print("\nConfusion Matrix:")
print(cm_ensemble)
print(f"\n✅ Detected: {cm_ensemble[1,1]}/{y.sum()} frauds ({cm_ensemble[1,1]/y.sum()*100:.1f}%)")
print(f"⚠️  False Alarms: {cm_ensemble[0,1]}")

# Cell 8: Recall-Focused Strategy
print("\n" + "="*60)
print("RECALL-FOCUSED STRATEGY (Catch More Frauds)")
print("="*60)

# Use lower threshold to catch more frauds
recall_threshold = np.percentile(best_ensemble_score, 95)  # Flag top 5%
recall_pred = (best_ensemble_score >= recall_threshold).astype(int)

recall_precision = precision_score(y, recall_pred, zero_division=0)
recall_recall = recall_score(y, recall_pred, zero_division=0)
recall_f1 = f1_score(y, recall_pred, zero_division=0)

print(f"\nRecall-Focused Performance (Flag top 5%):")
print(f"Threshold: {recall_threshold:.4f}")
print(f"Precision: {recall_precision:.4f}")
print(f"Recall   : {recall_recall:.4f}")
print(f"F1-Score : {recall_f1:.4f}")

cm_recall = confusion_matrix(y, recall_pred)
print("\nConfusion Matrix:")
print(cm_recall)
print(f"\n✅ Detected: {cm_recall[1,1]}/{y.sum()} frauds ({cm_recall[1,1]/y.sum()*100:.1f}%)")
print(f"⚠️  False Alarms: {cm_recall[0,1]}")
print(f"📊 Total Flagged: {recall_pred.sum()} transactions")

# Cell 9: Precision-Focused Strategy
print("\n" + "="*60)
print("PRECISION-FOCUSED STRATEGY (Fewer False Alarms)")
print("="*60)

# Use higher threshold for fewer false alarms
precision_threshold = np.percentile(best_ensemble_score, 99)  # Flag top 1%
precision_pred = (best_ensemble_score >= precision_threshold).astype(int)

precision_precision = precision_score(y, precision_pred, zero_division=0)
precision_recall = recall_score(y, precision_pred, zero_division=0)
precision_f1 = f1_score(y, precision_pred, zero_division=0)

print(f"\nPrecision-Focused Performance (Flag top 1%):")
print(f"Threshold: {precision_threshold:.4f}")
print(f"Precision: {precision_precision:.4f}")
print(f"Recall   : {precision_recall:.4f}")
print(f"F1-Score : {precision_f1:.4f}")

cm_precision = confusion_matrix(y, precision_pred)
print("\nConfusion Matrix:")
print(cm_precision)
print(f"\n✅ Detected: {cm_precision[1,1]}/{y.sum()} frauds ({cm_precision[1,1]/y.sum()*100:.1f}%)")
print(f"⚠️  False Alarms: {cm_precision[0,1]}")
print(f"📊 Total Flagged: {precision_pred.sum()} transactions")

# Cell 10: Final Strategy Selection
print("\n" + "="*60)
print("STRATEGY COMPARISON & SELECTION")
print("="*60)

strategy_comparison = pd.DataFrame({
    'Strategy': ['Balanced (Optimal F1)', 'Recall-Focused (Top 5%)', 'Precision-Focused (Top 1%)'],
    'Threshold': [best_ensemble_threshold, recall_threshold, precision_threshold],
    'Precision': [ensemble_precision, recall_precision, precision_precision],
    'Recall': [ensemble_recall, recall_recall, precision_recall],
    'F1-Score': [ensemble_f1, recall_f1, precision_f1],
    'Frauds_Detected': [cm_ensemble[1,1], cm_recall[1,1], cm_precision[1,1]],
    'False_Alarms': [cm_ensemble[0,1], cm_recall[0,1], cm_precision[0,1]],
    'Total_Flagged': [ensemble_pred.sum(), recall_pred.sum(), precision_pred.sum()]
})

print("\n", strategy_comparison.to_string(index=False))

# Recommendation based on use case
print("\n📋 RECOMMENDATIONS:")
print("\n1. RECALL-FOCUSED (Recommended for Fraud Detection):")
print(f"   • Catches {cm_recall[1,1]}/{y.sum()} frauds ({cm_recall[1,1]/y.sum()*100:.1f}%)")
print(f"   • Only {cm_recall[0,1]} false alarms out of {recall_pred.sum()} flagged")
print(f"   • Use this if: Missing frauds is very costly")

print("\n2. BALANCED:")
print(f"   • Catches {cm_ensemble[1,1]}/{y.sum()} frauds ({cm_ensemble[1,1]/y.sum()*100:.1f}%)")
print(f"   • {cm_ensemble[0,1]} false alarms")
print(f"   • Use this if: You want balance between catching frauds and avoiding false alarms")

print("\n3. PRECISION-FOCUSED:")
print(f"   • Catches {cm_precision[1,1]}/{y.sum()} frauds ({cm_precision[1,1]/y.sum()*100:.1f}%)")
print(f"   • Only {cm_precision[0,1]} false alarms")
print(f"   • Use this if: False alarms are very costly (customer experience)")

# Select recall-focused as default for fraud detection
selected_strategy = "Recall-Focused"
final_anomaly_score = best_ensemble_score
final_anomaly_pred = recall_pred
final_anomaly_threshold = recall_threshold

print(f"\n🎯 SELECTED STRATEGY: {selected_strategy}")
print(f"   Reason: Fraud detection prioritizes catching frauds over false alarms")

# Cell 11: Visualize Results
fig, axes = plt.subplots(2, 3, figsize=(18, 12))

# Score distribution
axes[0, 0].hist(best_ensemble_score[y==0], bins=50, alpha=0.6, label='Normal', color='blue')
axes[0, 0].hist(best_ensemble_score[y==1], bins=20, alpha=0.8, label='Fraud', color='red')
axes[0, 0].axvline(recall_threshold, color='green', linestyle='--', linewidth=2, label='Recall Threshold')
axes[0, 0].axvline(best_ensemble_threshold, color='orange', linestyle='--', linewidth=2, label='Balanced Threshold')
axes[0, 0].axvline(precision_threshold, color='purple', linestyle='--', linewidth=2, label='Precision Threshold')
axes[0, 0].set_xlabel('Anomaly Score')
axes[0, 0].set_ylabel('Frequency')
axes[0, 0].set_title('Optimized Ensemble Score Distribution')
axes[0, 0].legend()
axes[0, 0].set_yscale('log')

# ROC Curve
from sklearn.metrics import roc_curve
fpr, tpr, _ = roc_curve(y, best_ensemble_score)
axes[0, 1].plot(fpr, tpr, linewidth=2, label=f'Ensemble (AUC={ensemble_roc_auc:.3f})')
axes[0, 1].plot([0, 1], [0, 1], 'k--')
axes[0, 1].set_xlabel('False Positive Rate')
axes[0, 1].set_ylabel('True Positive Rate')
axes[0, 1].set_title('ROC Curve - Optimized Ensemble')
axes[0, 1].legend()
axes[0, 1].grid(True, alpha=0.3)

# Precision-Recall Curve
from sklearn.metrics import precision_recall_curve
prec_curve, rec_curve, _ = precision_recall_curve(y, best_ensemble_score)
axes[0, 2].plot(rec_curve, prec_curve, linewidth=2, label=f'Ensemble (AP={ensemble_pr_auc:.3f})')
axes[0, 2].set_xlabel('Recall')
axes[0, 2].set_ylabel('Precision')
axes[0, 2].set_title('Precision-Recall Curve')
axes[0, 2].legend()
axes[0, 2].grid(True, alpha=0.3)

# Confusion matrices
sns.heatmap(cm_recall, annot=True, fmt='d', cmap='Blues', ax=axes[1, 0],
            xticklabels=['Normal', 'Fraud'], yticklabels=['Normal', 'Fraud'])
axes[1, 0].set_title(f'Recall-Focused\n({cm_recall[1,1]}/{y.sum()} frauds caught)')

sns.heatmap(cm_ensemble, annot=True, fmt='d', cmap='Greens', ax=axes[1, 1],
            xticklabels=['Normal', 'Fraud'], yticklabels=['Normal', 'Fraud'])
axes[1, 1].set_title(f'Balanced\n({cm_ensemble[1,1]}/{y.sum()} frauds caught)')

sns.heatmap(cm_precision, annot=True, fmt='d', cmap='Oranges', ax=axes[1, 2],
            xticklabels=['Normal', 'Fraud'], yticklabels=['Normal', 'Fraud'])
axes[1, 2].set_title(f'Precision-Focused\n({cm_precision[1,1]}/{y.sum()} frauds caught)')

plt.tight_layout()
plt.savefig('tuned_anomaly_detection_results.png', dpi=300, bbox_inches='tight')
plt.show()

print("\n✅ Visualizations saved!")

# Cell 12: Final Summary
print("\n" + "="*60)
print("HYPERPARAMETER TUNING COMPLETE!")
print("="*60)

print("\n🎯 FINAL RESULTS:")
print(f"\nSelected Strategy: {selected_strategy}")
print(f"Frauds Detected: {cm_recall[1,1]}/{y.sum()} ({cm_recall[1,1]/y.sum()*100:.1f}%)")
print(f"Precision: {recall_precision:.1%}")
print(f"Recall: {recall_recall:.1%}")
print(f"F1-Score: {recall_f1:.4f}")
print(f"False Alarms: {cm_recall[0,1]} out of {recall_pred.sum()} flagged")

print("\n✅ Variables saved:")
print("   • final_anomaly_score: Anomaly scores for all transactions")
print("   • final_anomaly_pred: Binary predictions (0/1)")
print("   • final_anomaly_threshold: Selected threshold")
print("   • best_iso_model, best_lof_params, best_ocsvm_model: Tuned models")

print("\n🚀 Ready for final steps:")
print("   • Generate predictions for full dataset")
print("   • Create CSV/JSON outputs with fraud scores")
print("   • Feature importance analysis")

# Cell 1: Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import shap
import json
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

print("✅ Libraries imported!")

# Cell 2: Create Output DataFrame
print("\n" + "="*60)
print("CREATING OUTPUT FOR TRANSACTION VERIFIER")
print("="*60)

# Get individual model scores (from the tuned models)
feature_cols = ['step', 'amount', 'amount_log', 'day', 'hour',
                'type_CASH_IN', 'type_CASH_OUT', 'type_DEBIT',
                'type_PAYMENT', 'type_TRANSFER']

X = df[feature_cols].copy()
bool_cols = X.select_dtypes(include=['bool']).columns
X[bool_cols] = X[bool_cols].astype(int)

from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
X_scaled = scaler.fit_transform(X)

# Get scores from each model
print("Generating individual model scores...")

# Isolation Forest scores
iso_scores_raw = best_iso_model.score_samples(X_scaled)
iso_score = 1 - (iso_scores_raw - iso_scores_raw.min()) / (iso_scores_raw.max() - iso_scores_raw.min())

# LOF scores (need to refit to get scores for all data)
from sklearn.neighbors import LocalOutlierFactor
lof_model = LocalOutlierFactor(
    n_neighbors=best_lof_params['n_neighbors'],
    contamination=best_lof_params['contamination'],
    metric=best_lof_params['metric'],
    novelty=False,
    n_jobs=-1
)
lof_model.fit_predict(X_scaled)
lof_scores_raw = -lof_model.negative_outlier_factor_
lof_score = (lof_scores_raw - lof_scores_raw.min()) / (lof_scores_raw.max() - lof_scores_raw.min())

# One-Class SVM scores
ocsvm_scores_raw = -best_ocsvm_model.decision_function(X_scaled)
ocsvm_score = (ocsvm_scores_raw - ocsvm_scores_raw.min()) / (ocsvm_scores_raw.max() - ocsvm_scores_raw.min())

# Create output dataframe
output_df = pd.DataFrame({
    'idx': df['idx'],
    'ml_score': final_anomaly_score,  # Ensemble score (main score)
    'isolation_forest_score': iso_score,
    'lof_score': lof_score,
    'ocsvm_score': ocsvm_score,
    'anomaly_detected': final_anomaly_pred
})

print("✅ Output dataframe created!")
print(f"   Total transactions: {len(output_df)}")
print(f"   Columns: {list(output_df.columns)}")

print("\nSample output:")
print(output_df.head(10).to_string(index=False))

print("\n📊 Score Statistics:")
for col in ['ml_score', 'isolation_forest_score', 'lof_score', 'ocsvm_score']:
    print(f"   {col:25s}: mean={output_df[col].mean():.4f}, std={output_df[col].std():.4f}")

# Cell 3: SHAP Analysis
print("\n" + "="*60)
print("SHAP ANALYSIS")
print("="*60)

# Sample for SHAP analysis
sample_size = min(1000, len(X_scaled))
sample_indices = np.random.choice(len(X_scaled), sample_size, replace=False)
X_sample = X_scaled[sample_indices]

print(f"Calculating SHAP values for {sample_size} samples...")

# SHAP for Isolation Forest
explainer = shap.TreeExplainer(best_iso_model)
shap_values = explainer.shap_values(X_sample)

print("✅ SHAP values calculated!")

# Calculate feature importance
mean_abs_shap = np.abs(shap_values).mean(axis=0)
shap_importance_df = pd.DataFrame({
    'feature': feature_cols,
    'shap_importance': mean_abs_shap,
    'rank': range(1, len(feature_cols) + 1)
}).sort_values('shap_importance', ascending=False).reset_index(drop=True)
shap_importance_df['rank'] = range(1, len(feature_cols) + 1)

print("\n📊 Feature Importance (SHAP):")
print(shap_importance_df.to_string(index=False))

# Cell 4: Create SHAP Visualizations
print("\n" + "="*60)
print("CREATING SHAP VISUALIZATIONS")
print("="*60)

fig, axes = plt.subplots(2, 2, figsize=(16, 12))

# 1. SHAP Summary Plot (beeswarm)
plt.sca(axes[0, 0])
shap.summary_plot(shap_values, X_sample, feature_names=feature_cols, show=False)
axes[0, 0].set_title('SHAP Feature Impact (Summary)', fontsize=14, fontweight='bold')

# 2. SHAP Feature Importance Bar
plt.sca(axes[0, 1])
shap.summary_plot(shap_values, X_sample, feature_names=feature_cols,
                  plot_type="bar", show=False)
axes[0, 1].set_title('SHAP Feature Rankings', fontsize=14, fontweight='bold')

# 3. Model Score Comparison
axes[1, 0].scatter(output_df['isolation_forest_score'], output_df['ml_score'],
                   alpha=0.3, s=10, label='ISO vs Ensemble')
axes[1, 0].scatter(output_df['lof_score'], output_df['ml_score'],
                   alpha=0.3, s=10, label='LOF vs Ensemble')
axes[1, 0].scatter(output_df['ocsvm_score'], output_df['ml_score'],
                   alpha=0.3, s=10, label='OCSVM vs Ensemble')
axes[1, 0].plot([0, 1], [0, 1], 'k--', alpha=0.3)
axes[1, 0].set_xlabel('Individual Model Score')
axes[1, 0].set_ylabel('Ensemble ML Score')
axes[1, 0].set_title('Model Score Comparison', fontsize=14, fontweight='bold')
axes[1, 0].legend()
axes[1, 0].grid(True, alpha=0.3)

# 4. Score Correlation Heatmap
score_corr = output_df[['ml_score', 'isolation_forest_score', 'lof_score', 'ocsvm_score']].corr()
sns.heatmap(score_corr, annot=True, fmt='.3f', cmap='coolwarm',
            center=0, ax=axes[1, 1], cbar_kws={'label': 'Correlation'})
axes[1, 1].set_title('Model Score Correlations', fontsize=14, fontweight='bold')

plt.tight_layout()
plt.savefig('shap_and_model_analysis.png', dpi=300, bbox_inches='tight')
plt.show()

print("✅ Visualizations saved: shap_and_model_analysis.png")

# Cell 5: Save Output CSV
print("\n" + "="*60)
print("SAVING OUTPUT FILES")
print("="*60)

# Main output CSV for transaction verifier
csv_filename = 'anomaly_scores_for_verifier.csv'
output_df.to_csv(csv_filename, index=False)

print(f"✅ CSV saved: {csv_filename}")
print(f"   Rows: {len(output_df)}")
print(f"   Columns: {list(output_df.columns)}")
print(f"   Size: {output_df.memory_usage(deep=True).sum() / 1024:.2f} KB")

# Verify data integrity
print("\n✅ Data Integrity Checks:")
print(f"   All idx present: {len(output_df['idx'].unique()) == len(df['idx'].unique())}")
print(f"   No missing scores: {output_df['ml_score'].notna().all()}")
print(f"   No duplicate idx: {output_df['idx'].duplicated().sum() == 0}")
print(f"   Scores in [0,1]: {output_df['ml_score'].between(0, 1).all()}")

# Cell 6: Create JSON with SHAP Metadata
print("\n" + "="*60)
print("CREATING JSON OUTPUT")
print("="*60)

# Create comprehensive JSON
json_output = {
    'metadata': {
        'generation_date': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        'model_type': 'Ensemble Anomaly Detection',
        'models_used': ['Isolation Forest (50%)', 'LOF (30%)', 'One-Class SVM (20%)'],
        'threshold': float(final_anomaly_threshold),
        'total_transactions': int(len(output_df)),
        'anomalies_detected': int(output_df['anomaly_detected'].sum()),
        'detection_rate': float(output_df['anomaly_detected'].mean())
    },
    'shap_analysis': {
        'feature_importance': shap_importance_df.to_dict('records'),
        'top_3_features': list(shap_importance_df.head(3)['feature']),
        'interpretation': 'Features ranked by mean absolute SHAP value (impact on anomaly score)'
    },
    'score_statistics': {
        'ml_score': {
            'mean': float(output_df['ml_score'].mean()),
            'median': float(output_df['ml_score'].median()),
            'std': float(output_df['ml_score'].std()),
            'min': float(output_df['ml_score'].min()),
            'max': float(output_df['ml_score'].max()),
            'percentiles': {
                '90th': float(output_df['ml_score'].quantile(0.90)),
                '95th': float(output_df['ml_score'].quantile(0.95)),
                '99th': float(output_df['ml_score'].quantile(0.99))
            }
        }
    },
    'model_agreement': {
        'iso_lof_correlation': float(output_df[['isolation_forest_score', 'lof_score']].corr().iloc[0, 1]),
        'iso_ocsvm_correlation': float(output_df[['isolation_forest_score', 'ocsvm_score']].corr().iloc[0, 1]),
        'lof_ocsvm_correlation': float(output_df[['lof_score', 'ocsvm_score']].corr().iloc[0, 1])
    },
    'transactions': output_df.to_dict('records')
}

json_filename = 'anomaly_scores_with_shap.json'
with open(json_filename, 'w') as f:
    json.dump(json_output, f, indent=2)

print(f"✅ JSON saved: {json_filename}")
print(f"   Contains: metadata, SHAP analysis, statistics, all transactions")

# Cell 7: Create Summary for Verifier Agent
print("\n" + "="*60)
print("SUMMARY FOR TRANSACTION VERIFIER AGENT")
print("="*60)

summary = f"""
╔═══════════════════════════════════════════════════════════════╗
║         ANOMALY DETECTION OUTPUT - FOR VERIFIER AGENT         ║
╚═══════════════════════════════════════════════════════════════╝

📊 DATASET PROCESSED
├─ Total Transactions: {len(output_df):,}
├─ Anomalies Detected: {output_df['anomaly_detected'].sum()}
├─ Detection Rate: {output_df['anomaly_detected'].mean()*100:.2f}%
└─ Threshold Used: {final_anomaly_threshold:.4f}

🎯 OUTPUT FILES FOR VERIFIER
├─ {csv_filename}
│  └─ Contains: idx, ml_score, individual model scores, detection flag
│
├─ {json_filename}
│  └─ Contains: All scores + SHAP metadata + statistics
│
└─ shap_and_model_analysis.png
   └─ Contains: SHAP plots + model comparisons

📈 ML SCORE INTERPRETATION
├─ Range: 0.0 to 1.0
├─ Higher score = More anomalous = Higher fraud risk
│
├─ Score Thresholds:
│  ├─ 0.00 - 0.20: Low risk (normal transactions)
│  ├─ 0.20 - 0.29: Medium risk (monitor)
│  ├─ 0.29 - 0.50: High risk (review) ← Detection threshold
│  └─ 0.50 - 1.00: Very high risk (priority review)
│
└─ Distribution:
   ├─ Mean: {output_df['ml_score'].mean():.4f}
   ├─ Median: {output_df['ml_score'].median():.4f}
   ├─ 90th percentile: {output_df['ml_score'].quantile(0.90):.4f}
   ├─ 95th percentile: {output_df['ml_score'].quantile(0.95):.4f}
   └─ 99th percentile: {output_df['ml_score'].quantile(0.99):.4f}

🔍 TOP 3 FRAUD INDICATORS (SHAP Analysis)
"""

for idx, row in shap_importance_df.head(3).iterrows():
    summary += f"├─ {idx+1}. {row['feature']:20s} (SHAP: {row['shap_importance']:.4f})\n"

summary += f"""
🤖 MODEL DETAILS
├─ Ensemble Composition:
│  ├─ Isolation Forest: 50% weight
│  ├─ Local Outlier Factor: 30% weight
│  └─ One-Class SVM: 20% weight
│
├─ Individual Scores Included:
│  ├─ isolation_forest_score
│  ├─ lof_score
│  └─ ocsvm_score
│
└─ Model Agreement:
   ├─ ISO-LOF correlation: {json_output['model_agreement']['iso_lof_correlation']:.3f}
   ├─ ISO-OCSVM correlation: {json_output['model_agreement']['iso_ocsvm_correlation']:.3f}
   └─ LOF-OCSVM correlation: {json_output['model_agreement']['lof_ocsvm_correlation']:.3f}

💡 USAGE FOR VERIFIER AGENT
├─ 1. Load {csv_filename}
├─ 2. Use 'ml_score' as primary anomaly indicator
├─ 3. Consider individual model scores for confidence
├─ 4. Flag transactions where ml_score >= {final_anomaly_threshold:.4f}
├─ 5. Refer to SHAP analysis for feature importance
└─ 6. High model agreement (all 3 scores high) = Higher confidence

⚡ QUICK STATS
├─ Transactions flagged: {output_df['anomaly_detected'].sum()}
├─ Avg score (flagged): {output_df[output_df['anomaly_detected']==1]['ml_score'].mean():.4f}
├─ Avg score (not flagged): {output_df[output_df['anomaly_detected']==0]['ml_score'].mean():.4f}
└─ Score separation: {output_df[output_df['anomaly_detected']==1]['ml_score'].mean() - output_df[output_df['anomaly_detected']==0]['ml_score'].mean():.4f}

✅ DATA QUALITY
├─ All idx values preserved: ✓
├─ No missing scores: ✓
├─ No duplicate transactions: ✓
└─ Scores normalized to [0,1]: ✓

═══════════════════════════════════════════════════════════════
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Anomaly Detection Agent → Transaction Verifier Agent
═══════════════════════════════════════════════════════════════
"""

print(summary)

# Save summary
summary_filename = 'verifier_handoff_summary.txt'
with open(summary_filename, 'w') as f:
    f.write(summary)

print(f"\n✅ Summary saved: {summary_filename}")

# Cell 8: Show Sample Outputs
print("\n" + "="*60)
print("SAMPLE OUTPUTS FOR VERIFICATION")
print("="*60)

print("\n🔴 HIGH ANOMALY SCORES (Top 10):")
high_scores = output_df.nlargest(10, 'ml_score')
print(high_scores.to_string(index=False))

print("\n🟢 LOW ANOMALY SCORES (Sample 10):")
low_scores = output_df.nsmallest(10, 'ml_score').sample(min(10, len(output_df.nsmallest(10, 'ml_score'))))
print(low_scores.to_string(index=False))

print("\n🟡 FLAGGED TRANSACTIONS (Sample 10):")
flagged = output_df[output_df['anomaly_detected'] == 1].sample(min(10, output_df['anomaly_detected'].sum()))
print(flagged.to_string(index=False))

# Cell 9: Final Checklist
print("\n" + "="*60)
print("FINAL CHECKLIST")
print("="*60)

checklist = {
    'idx values preserved': len(output_df['idx'].unique()) == len(df['idx'].unique()),
    'ml_score for all transactions': output_df['ml_score'].notna().all(),
    'Individual model scores included': all(col in output_df.columns for col in ['isolation_forest_score', 'lof_score', 'ocsvm_score']),
    'SHAP analysis completed': len(shap_importance_df) > 0,
    'CSV file created': True,
    'JSON file created': True,
    'Visualization created': True,
    'No missing values': not output_df.isnull().any().any(),
    'No duplicate idx': output_df['idx'].duplicated().sum() == 0,
    'Scores in valid range': output_df['ml_score'].between(0, 1).all()
}

print("\n✅ Deliverables Checklist:")
for item, status in checklist.items():
    status_icon = "✓" if status else "✗"
    print(f"   [{status_icon}] {item}")

print("\n📁 Files Ready for Transaction Verifier:")
print(f"   1. {csv_filename} (Main data file)")
print(f"   2. {json_filename} (Complete data + metadata)")
print(f"   3. shap_and_model_analysis.png (Visualizations)")
print(f"   4. {summary_filename} (Handoff documentation)")

print("\n" + "="*60)
print("🎉 OUTPUT READY FOR TRANSACTION VERIFIER AGENT!")
print("="*60)

print(f"""
╔═══════════════════════════════════════════════════════════════╗
║                    HANDOFF COMPLETE!                          ║
╠═══════════════════════════════════════════════════════════════╣
║  ✓ {len(output_df):,} transactions scored                                ║
║  ✓ {output_df['anomaly_detected'].sum()} anomalies flagged                                   ║
║  ✓ 4 model scores per transaction                            ║
║  ✓ SHAP feature importance included                          ║
║  ✓ All idx values preserved                                  ║
║  ✓ Ready for transaction verifier agent                      ║
╚═══════════════════════════════════════════════════════════════╝

Next Agent: Transaction Verifier
Input Files: {csv_filename}, {json_filename}
Priority: Review transactions with ml_score >= {final_anomaly_threshold:.4f}

Anomaly Detection Complete! 🚀
""")

# ===============================================
# SAVE TRAINED MODELS + DOWNLOAD OUTPUT FILES (Colab)
# ===============================================
import joblib
from google.colab import files

# ✅ 1. Save trained models locally
joblib.dump(best_iso_model, "best_iso_model.pkl")
joblib.dump(best_lof_params, "best_lof_params.pkl")  # LOF params only (model not reusable without refit)
joblib.dump(best_ocsvm_model, "best_ocsvm_model.pkl")

print("✅ Models saved as .pkl files")
# ✅ 2. Download models
files.download("best_iso_model.pkl")
files.download("best_lof_params.pkl")
files.download("best_ocsvm_model.pkl")

# ✅ 3. Download key output files
files.download("anomaly_scores_for_verifier.csv")
files.download("anomaly_scores_with_shap.json")
files.download("verifier_handoff_summary.txt")
files.download("shap_and_model_analysis.png")

print("\n🎯 All models and output files ready for local transfer to VS Code.")

